name:                quantum-shogi
version:             0.1.0.0
github:              "na2hiro/quantum-shogi"
license:             BSD3
author:              "na2hiro"
maintainer:          "a@81.la"
copyright:           "2013-2020 na2hiro"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/na2hiro/quantum-shogi#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl

library:
  source-dirs: src

executables:
  quantum-shogi-exe:
    main:                quantumclient.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quantum-shogi
    - json

tests:
  quantum-shogi-test:
    main:                quantumSpec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quantum-shogi
    - hspec
